version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://david:david@cluster0.fc1tbhb.mongodb.net/meantattoos
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "3001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
