// Generated by https://quicktype.io

export interface Tato {
  _id:         string;
  title:       string;
  description: string;
  price:       number;
  //style:       Style;
  imageUrl?:      string;
}

/*export enum Style {
  Acuarela = "Acuarela",
  EstiloMexicanoTradicional = "Estilo mexicano tradicional",
  EstiloTradicionalBN = "Estilo tradicional b/n",
}*/
