// Generated by https://quicktype.io

export interface Tato {
  id:          string;
  title:       string;
  description: string;
  price:       number;
  details:     Details;
  image?:       string;
}

export interface Details {
  size:  string;
  color: string;
  style: Style;
}

export enum Style {
  Acuarela = "Acuarela",
  EstiloMexicanoTradicional = "Estilo mexicano tradicional",
  EstiloTradicionalBN = "Estilo tradicional b/n",
}
